### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by waelio** [bradtraversy/microposts_fullstack_vue#3]
./src/services/historyService.js 19:20
Module parse failed: Can not use keyword 'await' outside an async function (19:20)
You may need an appropriate loader to handle this file type.
>      return new Promise(function (resolve, reject) {
>        try {
>           var res = await axios.get(url);
>          var data = res.data;
>           resolve(data.map(function (history) {

**Comment by AndreasDeveloper** [comment]
Just simply make function async.

return new Promise(async (resolve, reject) => {...

**Comment by waelio** [comment]
Thanks
